### ISSUE TITLE
.env sample is wrong

### ISSUE THREAD

**Issue by michaelmwu-stripe** [stripe-samples/oxxo-payment#13]
https://github.com/stripe-samples/oxxo-payment/blob/fdc5cc9db00568a31ea251e6e0275df010264aad/.env.example#L7

This should be `../client` as there is no `web` directory anymore

**Comment by cernalue** [comment]
> https://github.com/stripe-samples/oxxo-payment/blob/fdc5cc9db00568a31ea251e6e0275df010264aad/.env.example#L7
> 
> This should be `../client` as there is no `web` directory anymore

If you cloned the project the **env.example** should be copied into the directory of the server language you chose (this will move the file two directories) but `web` doesn't exist. The correct value will be: 

`STATIC_DIR=../../client/`

**Comment by cjavilla-stripe** [comment]
Fixed. Thanks, both!
